ewm main server
BorodaPT/java-explore-with-me pull request #4
Opened 2023-09-13 16:26 UTC by BorodaPT

1. реализован ewm-server с радилением на модули : main_ewm_server и main_ewm_module(для возможного последующего обмена между ewm_gateway и main_ewm_server)
2. Контроллеры разбиты согласно смысловой направленности и пути эндойнстов:
- эндпойнты admin
- эндпойнты залогированных пользователей
- эндпойнты публичные
3. Сервисы по работе с DB разнесены по имеющиемся в функционале сущностям.
4. Реализован отдельный пакет c классами обработки ошибок параметров и значиний по работе с сущностями
5. Дополнительно в dtoHit сервиса статистики был добавлен сонструктор без id.

2023-09-17 21:07 UTC, db-exp requested changes

2023-09-17 21:07 UTC, db-exp commented on main_ewm/main_ewm_service/src/main/java/ru/practicum/services/compilations/ServiceCompilationImpl.java
> +        if (newCompilationDto.getTitle() == null || newCompilationDto.getTitle().isBlank()) {
тут тоже лучше проверить аннотациями

2023-09-17 21:07 UTC, db-exp commented on main_ewm/main_ewm_service/src/main/java/ru/practicum/controller/ControllerUser.java
> +public class ControllerUser {
минорное - лучше UserEventsController, то есть отразить в названии суть и словом Controller закончить.
Для двух других контроллеров тоже справедливо - лучше PublicController, AdminController

2023-09-18 05:30 UTC, BorodaPT commented on pom.xml
> +        <module>main_ewm</module>
странно, в среде нормально отображается. Переписал, может где то табуляция или пробелы так повлияли

2023-09-18 05:31 UTC, BorodaPT commented on main_ewm/main_ewm_service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users CASCADE;
да, понимаю, простите. В прошлом спринте наткнулся что когда запрос был не в одну строку, он не воспринимался, поэтому тут так же сделал сразу. Попробую отформатировать и посмотрю, все ли запустится.

2023-09-18 05:46 UTC, BorodaPT commented on main_ewm/main_ewm_service/src/main/java/ru/practicum/services/compilations/ServiceCompilationImpl.java
> +        if (newCompilationDto.getTitle() == null || newCompilationDto.getTitle().isBlank()) {
Здесь была проблема что в момент изменения ни одно из полей не является обязательным, поэтому использовать для редактирования то же  Dto с аннотациями нельзя было. Вместо создания дополнительного Dto перенес проверки в методы класса. 
ТОгда для Dto создания добавлю аннотации а для изменения новый dto сделаю

2023-09-18 07:02 UTC, BorodaPT commented on main_ewm/main_ewm_service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users CASCADE;
Выявить оперативно не удалось причину. Обратился в Пачку за консультацией. 
Если иных замечаний не будет, пожалуйста примите, постараюсь выявить причину проблем форматирования к моменту сдачи 3-й части

2023-09-18 10:52 UTC, db-exp approved these changes

2023-09-18 11:11 UTC, merged